### PR TITLE
Add gist.github.com support

### PR DESCRIPTION
**Pull request by darkred**
Currently the extension is not working in gist.github.com pages, 
i.e. there's no notification number in the blue bubble nor pop-over on hover.

This PR adds `https://gist.github.com/*` in the extension's manifest.json.
<sup>(I hope this change is all that's needed, because I couldn't get the loaded unpacked extension to work, I was getting errors)</sup>

Test URL:
https://gist.github.com/discover

Thank you

### CODE REVIEW

**Comment by tanmayrajani** [comment]
Hi, so I checked and it seems it's not the only change needed (as you suspected as well).. 

notice the following, it's using `location.origin` for building the URL to get notifications. Which doesn't work on `gist.github.com`. 
https://github.com/tanmayrajani/notifications-preview-github/blob/master/extension/github-notifications-preview.js#L16

**Comment by darkred** [comment]
Thank you for responding and for identifying that problem.
Could you please tell me how to build the extension locally,
in order to make sure that the extension works, before I add the commit to this PR ?

**Comment by tanmayrajani** [comment]
I noticed the same problem today for the local build but didn't have enough time at my hand to figure out and fix. If you can, see if you're able to fix that first. Maybe @fregante can help as well? As a last resort, you'll still be able to build and import the dist folder for now?

**Comment by darkred** [comment]
> Maybe @fregante can help as well?

For reference, here is how I do `Load Unpacked` the "Extension" folder in Google Chrome, and the errors I get:

- download the repo as ZIP, and extract it,
- if I "Load Uppacked" the "extension" subfolder, `I get Unrecognized manifest key 'applications` ..
- .. so navigate to the `extension` folder, open `manifest.json` and remove the `"applications"` key 

Then, if I try to `Load Unpacked` the "extension" folder again
I now get `Uncaught SyntaxError: Cannot use import statement outside a module` at `options-storage.js:1`

---

> As a last resort, you'll still be able to build and import the dist folder for now?

How do I do that? Which dist folder do you mean?

---

> see if you're able to fix that first.

I'll try

**Comment by fregante** [comment]
The extension needs to be built first:
1. Run `npm install`
2. Run `npm run build`

Then loaded from the new `dist` folder that has been generated, not `extension`

> I noticed the same problem today for the local build

It seems to work correctly for me and on GitHub Actions. You might just need to delete `node_modules`

**Comment by darkred** [comment]
Thank you very much @fregante .
It works fine with your instructions *(I also opened `manifest.json` and removed the `"applications"` key in the `dist` folder)*.

---

Now regarding the issue that @tanmayrajani kindly described:
I can only think of changing in https://github.com/tanmayrajani/notifications-preview-github/blob/master/extension/github-notifications-preview.js#L16 the `location.origin` to fixed `https://github.com`
but the extension still doesn't work: 
if I open e.g. https://gist.github.com/discover, I get this error `Uncaught (in promise) TypeError: Failed to fetch` :

<details>
<summary>the main error</summary>


</details>

*because of "Cross-Origin Read Blocking (CORB)":*



which leads to `Uncaught (in promise) TypeError: Cannot read property 'textContent' of null`, i.e.:
<details>
<summary>the 2nd error</summary>


</details>

&nbsp;

Sorry I can't be of any more help.

**Comment by fregante** [comment]
> _I also opened `manifest.json` and removed the `"applications"` key in the `dist` folder)_.

That's not necessary. Chrome complains but it still works

> _because of "Cross-Origin Read Blocking (CORB)":_

Ugh, that's an annoying problem and that probably means it's not possible.

In my `npmhub` extension we fixed that by moving the fetch to the `background` page (https://github.com/npmhub/npmhub/issues/92), however this is not possible here: we **need** the current page’s cookies and those are not available in the `background` page.

AFAIK, there are only 3 solutions:

- We rewrite the extension to use the API instead (ideal, but it means a complete and much lengthier rewrite)
- GitHub adds a `Access-Control-Allow-Origin` header (heh, it won't happen)
- Add `request`-related permissions to be able to add the header ourselves: https://stackoverflow.com/a/54835157/288906 but it's not worth it because it causes "This extension can see all your web activity"

Other than that, I don't see a solution, but feel free to keep looking for one.

**Comment by fregante** [comment]
I'll close this PR in the meanwhile, it's not enough

**Pull request closed without merging**
