### PR TITLE
Avoid scrollable content

### PR DESCRIPTION
**Pull request by bfred-it**
Nested scrollviews are a bit annoying. Perhaps we can just leave it open and the user can scroll the whole page instead of a tiny _view_.

### CODE REVIEW

**Comment by tanmayrajani** [comment]
Yes, I actually had it this way until Sindre suggested to make it scrollable on the module-requests issue.. I also prefer this way

**Comment by bfred-it** [comment]
Ah true:

> It should have a limited height, maybe half the page height and the content should scroll if it exceeds that.
> @sindresorhus in https://github.com/sindresorhus/module-requests/issues/100#issuecomment-323301260

Sindre what do you say? Do you use this extension?

**Comment by sindresorhus** [comment]
> Sindre what do you say? Do you use this extension?

I still think it should be scrollable, but I don't use this, so my opinion is not important.

**Comment by bfred-it** [comment]
Let's merge this then until someone else comes with more opinions

**Pull request merged**
