### PR TITLE
Show less intrusive loading indicator

### PR DESCRIPTION
**Pull request by bfred-it**
bell

### CODE REVIEW

**Comment by tanmayrajani** [comment]
Looks great! :clap: :clap: 

I've updated the extension package on webstore with latest (till this).

**Comment by bfred-it** [comment]
Great! I think I'm done for now anyway :) 

Locally I'm using a smaller version without avatars and date to make it more compact, but some may want that information.

**Comment by bfred-it** [comment]
For reference:

screen shot 2017-08-28 at 14 18 25

```css
#NPG-dropdown {
	width: auto;
	padding: 5px;
}
#NPG-item .boxed-group {
	margin-bottom: 6px;
}
#NPG-item .list-group-item-name {
	padding-right: 15px;
}
#NPG-item .age,
#NPG-item .avatar-stack {
	display: none;
}
```

**Comment by tanmayrajani** [comment]
looks neat.. maybe we could provide an option to use this view?

**Pull request merged**
