### PR TITLE
Preview notification count

### LINKED ISSUE #19: Preview notification count
Depends on #17 

notification count preview

CSS used in the screenshot (+ the number in the dom)

```css
.unread {
    top: -5px;
    left: 11px;
    font-size: 13px;
    line-height: 0.8;
    color: transparent;
    font-weight: bold;
    -webkit-background-clip: text;
    border: none;
    border-radius: 0;
}
```

### PR DESCRIPTION
**Pull request by bfred-it**
Closes #19 

Here's a quick preview of what it looks like with a few numbers:

a

Untested with paginated notifications. In that case it could add a **+** or just use **∞** 😄

### CODE REVIEW

**Comment by bfred-it** [comment]
@yakov116 I made it 20% brighter:

screen shot 2017-09-13 at 16 29 43

**Comment by yakov116** [comment]
@bfred-it match the gray I like best

**Comment by bfred-it** [comment]
@yakov116 removing the color makes the notifications blend in too much. I'm going to leave it as is since it matches the original color.

Customizations can be made with Stylish:

```css
.notification-indicator .mail-status.unread:not(:empty) {
    background-color: rgba(255,255,255,0.75);
    background-image: none;
}
```

**Comment by bfred-it** [comment]
Before I publish a new version to the Chrome Web Store, which one do you prefer?

Current:

just text

More standard style, but smaller number

round round 10

Currently on branch https://github.com/tanmayrajani/notifications-preview-github/tree/count-style

**Comment by tanmayrajani** [comment]
How about white colored font in that blue background circle? How does that look as compared to these?

**Comment by bfred-it** [comment]
:-/
 
screen shot 2017-09-13 at 21 04 39

**Comment by yakov116** [comment]
@tanmayrajani Brillant!

**Comment by bfred-it** [comment]
Like this? No

screen shot 2017-09-13 at 21 06 47

**Comment by yakov116** [comment]
@bfred-it Your right doesn't look good

**Comment by tanmayrajani** [comment]
Hmm, black (with the circle) looks better in the three options, we can go with that for now.. I guess

**Comment by yakov116** [comment]
@tanmayrajani Gray or white inside?

**Comment by yakov116** [comment]
@bfred-it the blow happene after I updated (it only happened once)
image

**Comment by bfred-it** [comment]
Can you open a new issue? I think I know why

**Pull request merged**
