### PR TITLE
fix: indicator doesn't update after mask as read

### LINKED ISSUE #147: Notification status doesn't update after clicking `Mark as Read` button
After clicking `Mark as Read` button, the notification status doesn't update, it still keeps the unread notifications status.

You have to refresh the page to update the status.

image

Hi @tanmayrajani, thanks for this excellent extension, it's very convenient.

Could you take a look when you are have time, or give me some clues to investigate this issue.

### PR DESCRIPTION
**Pull request by tjx666**
fix #147

### CODE REVIEW

**Comment by fregante** [comment]
Thank you 🙏

**Comment by euxx** [comment]
Hi @tjx666 , thanks for handling this, but it seems there are still issues.

Notification status still doesn't get updated after clicking Mark as Read button.

I inspected the dot indicator and found `--notifications-icon-indicator-display` is always `none`， even when there are unread notifications. 

image

I don't know how to debug extension locally, could you take another look?

**Comment by tjx666** [comment]
Will investgate it when I have free time

**Comment by tjx666** [comment]
@euxx https://github.com/fregante/notifications-preview-github/pull/157

**Comment by euxx** [comment]
> @euxx #157

That's great. Thanks you!

**Pull request merged**
